SYS_INVALID = 0
DRONE_NUMBER = 3
WAIT_TO_CONNECT = 2
DRONE_COM = "topicDroneCom22"
LSTWILLMSG = "LastWillMessageType"
INITMSG = "InitMessageType"
CMD        = "CommandType"
MASTERLSTWIL = "MasterLastWillMessageType"
FBINFO = "feedBackInfo "

ADD_CONNECT = 1
SUB_CONNECT =-1 

TYPE_CLIENT_INIT = 0
TYPE_CLIENT_NORMAL = 1
TYPE_CLIENT_MASTER =2 
MASTER_ONLINE = 1
MASTER_OFFLINE = 0
TOPIC_LAST_WILL = "Drone/LastWill"
ALL_DRONE_ACTIVATED = 1

SEND_INIT_SUCCESS = 1
NOT_SEND_INIT = 0 


CONNECT_SUCCESS = 1
CONNECT_FAILED = 0

ON  = 1 
OFF = 0

MAX_TRIAL = 5

ALL  = "ALL_UNIT_SELECT"
UNIT  = "EACH_DRONE_SELECT"