SYS_INVALID = 0
DRONE_NUMBER = 2
WAIT_TO_CONNECT = 2
SYS_COM = "topicSystemCom"
DRONE_COM = "topicDroneCom22"
CONTROL_COM = "topicControlCom"
LSTWILLMSG = "LastWillMessageType"
INITMSG = "InitMessageType"
INFO = "InfoMessageType"
REPORTMSG = "SystemReportMessageType"
YAWVALUE = "YawValueMessageType"
CMD        = "CommandType"

DONE = 1

MASTERLSTWIL = "MasterLastWillMessageType"

ADD_CONNECT = 1
SUB_CONNECT =-1 

TYPE_CLIENT_INIT = 0
TYPE_CLIENT_NORMAL = 1
TYPE_CLIENT_MASTER =2 
TYPE_CLIENT_INFO =3


MASTER_ONLINE = 1
MASTER_OFFLINE = 0
TOPIC_LAST_WILL = "Drone/LastWill"
ALL_DRONE_ACTIVATED = 1

SEND_INIT_SUCCESS = 1
NOT_SEND_INIT = 0 


CONNECT_SUCCESS = 1
CONNECT_FAILED = 0

ON  = 1 
OFF = 0
ALL = "ALL"
UNIT = "UNIT"
PRIORITY = "PRIORITY"